# Generated by Django 2.2.9 on 2020-01-29 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members_area', '0004_auto_20200128_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members_area.Course'),
        ),
    ]
