# Generated by Django 2.2.9 on 2020-02-20 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members_area', '0016_auto_20200216_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='video',
        ),
        migrations.AddField(
            model_name='lesson',
            name='resources',
            field=models.FileField(blank=True, null=True, upload_to='resources/'),
        ),
    ]
